---
title: "Model Testing Summary"
author: "Topher Weiss-Lehman"
date: ""
output: pdf_document
---

\begin{center}
    \begin{tabular}{ | p{3.5cm} | p{8.9cm} | p{3.5cm} |}
    \hline
    \bf{Functionality tested} & \bf{Test details} & \bf{Test outcome} \\
    \hline
    SaveParams() & SaveParams.R tests that all input parameters are delisted and saved in an executable file that can be later read into R & `r readLines("SaveParams.txt")` \\
    \hline
    ChangeClimate() & ChangeClimate.R tests both the functionality and ability to return useful error messages of the ChangeClimate function & `r readLines("ChangeClimate.txt")` \\
    \hline
    PopMatColNames() & PopMatColNames.R checks the example functionality as well as the proper output for different numbers of fitness and dispersal alleles & `r readLines("PopMatColNames.txt")` \\
    \hline
    Initialize() & Initialize.R checks for correct dimensionality of generated population matrices and tests that the values generated for the matrix conform to given parameters such as specified distributions and sex ratios & `r readLines("Initialize.txt")` \\
    \hline
    GetEnvQual() \& CalcEnvMean() & EnvCalcFxns.R tests both of these functions by checking for symmetry and equivalence across spatial scales & `r readLines("EnvCalcFxns.txt")` \\
    \hline
    CalcTraits() & CalcTraits.R tests the dimenstionality of the output and the distributional accuracy of the function & `r readLines("CalcTraits.txt")` \\
    \hline
    Disperse() & Disperse.R tests the distinction among the three possible dispersal kernels as well as the effect of increasing landscape width on dispersal patterns & `r readLines("Disperse.txt")` \\
    \hline
    RelFit() & RelFits.R tests the range of values returned by RelFit() and the effect of increasing or decreasing the degree of local adaptation and the amount of trait variance present on the calculated fitnesses & `r readLines("RelFits.txt")` \\
    \hline
    Inheritence() & Inheritence.R tests for correct segregation of independent alleles as well as correct behavior in the mutation process & `r readLines("Inheritence.txt")` \\
    \hline
    MatFill() & MatFill.R tests for the correct dimensionality of the returned matrices and the correct elements in them based on input parents, locations, etc. & `r readLines("MatFill.txt")` \\
    \hline
    Reproduce() & Reproduce.R checks for helpful error messages, cases for which there should be zero growth on average, and detioriating growth with increased distance from an optimum due to local adaptation & `r readLines("Reproduce.txt")` \\
    \hline
    No dispersal & NoDisperse.R uses the full model to test the case of zero dispersal and ensure that populations do not leave their staring patch & `r readLines("NoDisperse/NoDisperse.txt")` \\
    \hline
    Stationary range & StationaryRange.R uses the full model to check that populations with the ability to grow and disperse fill up a stationary range boundary, but do not move beyond it & `r readLines("StationaryRange/StationaryRange.txt")` \\
    \hline
    Moving environment & MovingEnv.R uses the full model to check that populations with the ability to grow, but not disperse, react to a moving environment by eventually going extinct & `r readLines("MovingEnv/MovingEnv.txt")` \\
    \hline
    \end{tabular}
\end{center}

